# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/psledblink/psledblink.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==psledblink || ORIG_REF_NAME==psledblink} -quiet] -quiet

# IP: bd/psledblink/ip/psledblink_processing_system7_0_0/psledblink_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==psledblink_processing_system7_0_0 || ORIG_REF_NAME==psledblink_processing_system7_0_0} -quiet] -quiet

# XDC: bd/psledblink/psledblink_ooc.xdc
