# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/timerzybo/timerzybo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerzybo || ORIG_REF_NAME==timerzybo} -quiet] -quiet

# IP: bd/timerzybo/ip/timerzybo_processing_system7_0_0/timerzybo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerzybo_processing_system7_0_0 || ORIG_REF_NAME==timerzybo_processing_system7_0_0} -quiet] -quiet

# XDC: bd/timerzybo/timerzybo_ooc.xdc
