# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/zybodevelopment/psledblink/psledblink.srcs/sources_1/bd/psledblink/ip/psledblink_processing_system7_0_0/psledblink_processing_system7_0_0.xci
# IP: The module: 'psledblink_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zybodevelopment/psledblink/psledblink.srcs/sources_1/bd/psledblink/ip/psledblink_processing_system7_0_0/psledblink_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'psledblink_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/zybodevelopment/psledblink/psledblink.srcs/sources_1/bd/psledblink/ip/psledblink_processing_system7_0_0/psledblink_processing_system7_0_0.xci
# IP: The module: 'psledblink_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zybodevelopment/psledblink/psledblink.srcs/sources_1/bd/psledblink/ip/psledblink_processing_system7_0_0/psledblink_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'psledblink_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
