# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ledbllinky/ledbllinky.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky || ORIG_REF_NAME==ledbllinky} -quiet] -quiet

# IP: bd/ledbllinky/ip/ledbllinky_processing_system7_0_0/ledbllinky_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky_processing_system7_0_0 || ORIG_REF_NAME==ledbllinky_processing_system7_0_0} -quiet] -quiet

# IP: bd/ledbllinky/ip/ledbllinky_axi_gpio_0_0/ledbllinky_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky_axi_gpio_0_0 || ORIG_REF_NAME==ledbllinky_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ledbllinky/ip/ledbllinky_ps7_0_axi_periph_0/ledbllinky_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky_ps7_0_axi_periph_0 || ORIG_REF_NAME==ledbllinky_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ledbllinky/ip/ledbllinky_rst_ps7_0_50M_0/ledbllinky_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky_rst_ps7_0_50M_0 || ORIG_REF_NAME==ledbllinky_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ledbllinky/ip/ledbllinky_auto_pc_0/ledbllinky_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ledbllinky_auto_pc_0 || ORIG_REF_NAME==ledbllinky_auto_pc_0} -quiet] -quiet

# XDC: bd/ledbllinky/ledbllinky_ooc.xdc
